### ISSUE TITLE
Accuracy of Distance Calculations

### ISSUE THREAD

**Issue by JonathanJJudge** [arjunmehta/node-geo-proximity#12]
Hi, I've really enjoyed using your module. Runs really fast. However, I have been separately calculating the distance between Point A (the search epicenter) and Point B (the search results within the 10 mile radius or approximately 16000 meter radius) and the results are off by a few miles and I'm hoping you could offer guidance as to what might be causing it.

For instance, here's my function call:

```javascript
proximity.nearby(zipCodeData.latitude, zipCodeData.longitude, 16000, ... });
```

For ZIP Code 11230, the coordinates are longitude: -73.96427, latitude: 40.622994,

Here's what Redis returns when I set the `values` option for the `nearby` method to `true`:

```javascript
[ [ '5526dfb4a1a2b38f7615bcbb',
    40.6366990506649,
    -74.03548389673233 ],
  [ '5526e642ac21e0997f329946',
    40.72834476828575,
    -74.17629450559616 ],
  [ '55245478f5b931ab483b668b',
    40.70272162556648,
    -73.9868876338005 ],
  [ '55245c27073f057f821d8235',
    40.70272162556648,
    -73.9868876338005 ],
  [ '552701f4efc23135b6acaec0',
    40.584060698747635,
    -73.6943444609642 ] ]
```

When I check to see if these values are within the 16000 meter radius using the function below, a couple of them are beyond that. 

```javascript
function distance(lat1, lon1, lat2, lon2, unit) {
  var radlat1 = Math.PI * lat1/180
  var radlat2 = Math.PI * lat2/180
  var radlon1 = Math.PI * lon1/180
  var radlon2 = Math.PI * lon2/180
  var theta = lon1-lon2
  var radtheta = Math.PI * theta/180
  var dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);
  dist = Math.acos(dist)
  dist = dist * 180/Math.PI
  dist = dist * 60 * 1.1515
  if (unit=="K") { dist = dist * 1.609344 }
  if (unit=="N") { dist = dist * 0.8684 }
  return dist;
}       
```

Any idea why?

**Comment by arjunmehta** [comment]
Hi there @JonathanJJudge 
Unfortunately that is expected behavior. This module uses 2D Spatial indexing based on geohash size. Each of the various "steps" in geohash bit depth relate to a box size, and this is actually what is used to **approximate** nearby points.

Here is a write up on how this module works: http://23.239.12.206:8000/posts/2014-04-05-geohash-proximity-pt2.html

Please let me know if this helps in understanding what's going on.

Unfortunately it's one of the tradeoffs of the fast algorithm, it's not entirely accurate.

**Comment by JonathanJJudge** [comment]
Ok, that's not a problem per se, and I think I get the jist of it now. 

How can I identify or set what bit-depth I am using and therefore what the rough radius steps are, so I know if the search should be done instead in 5 mile increments or even 10 mile increments as an alternative to something more precise?

Thank you for your response, @arjunmehta!

**Comment by arjunmehta** [comment]
There is currently no method to search by bitDepth, but you can see how they are stepped here:
https://github.com/arjunmehta/node-geo-proximity/blob/master/lib/range.js#L5-L31

ie. 52bit geohash ~= 0.6m, 50bit geohash ~= 1m etc...

This is an index that generally equates a radius to a bit depth. Hopefully knowing how it steps up can be useful to you?
