### ISSUE TITLE
Delete Set?

### ISSUE THREAD

**Issue by ksabariraj** [arjunmehta/node-geo-proximity#13]
Hi,

Thanks for the great module.

Is any function available to remove Set like "proximity.deleteSet('place1')"?

In my case, I have created Multiple Sets like place1, place2 etc... with some locations. After some time, I need to update the same place1 set with some new location details. When I tried to update the new locations, the old locations details also existing. 

Having Multiple Set with out deleting them from RedisDB when it is not needed will reduce the performance?

Thanks,
sabari.

**Comment by arjunmehta** [comment]
Hi there @ksabariraj 

This is a good idea. I can add a `removeSet` method to the module soon. It's an easy thing to add.
Having multiple redis zSets will not necessarily reduce the performance for you, but it will use more memory than needed, so having a way to delete unused sets is a good idea!

I'll add this in the next few days.

Thanks!
Arjun

**Comment by ksabariraj** [comment]
Hi Arjun,

Thanks for the update. 

And one more thing, is it possible to store some other data like below.

[43.6667, -79.4167,  'Toronto', [object]]

Thanks,
Sabari.

**Comment by arjunmehta** [comment]
@ksabariraj Unfortunately that would be really complicated and outside the scope of this module. I suggest you create another set of items (either on redis or as a local JavaScript object) that you can use to store metadata about a location.

**Comment by arjunmehta** [comment]
Added to `delete` and `deleteSet` methods in [geo-proximity@2.2.0](https://www.npmjs.com/package/geo-proximity)

**Comment by ksabariraj** [comment]
Hi Arjun,

Thanks for your time and update.

Thanks,
Sabari.

**Comment by arjunmehta** [comment]
@ksabariraj Of course! Thank you for the suggestion/request :)
