### ISSUE TITLE
Question to the rangeindex

### ISSUE THREAD

**Issue by hellocomrade** [arjunmehta/node-geo-proximity#21]
Hi,

This might just be a question instead of an issue:

in https://github.com/arjunmehta/node-geo-proximity/blob/master/lib/range.js,

How did you come from the rough estimate in rangeIndex array? Are those numbers diameter or radius? From the way they are used in the source, it appears they are radius.

However, using the code from geohash-Int (https://github.com/yinqiwen/geohash-int),

   for(int i=0;i < 65; i+=2)
    {
        idd = naiveEncodeGeohash(4842397.8495074, -10601981.5353662, i, wmRange);
        Envelope e = naiveDecodeGeohash(idd, i, wmRange);
        cout << i << " : (" << (e.xmax - e.xmin) << ", " << (e.ymax - e.ymin) << endl;
    }

I can get a list of values that should be diameter, which are very close to your list.

0 : (40075016.680000, 40075016.680000)
2 : (20037508.340000, 20037508.340000)
4 : (10018754.170000, 10018754.170000)
6 : (5009377.085000, 5009377.085000)
8 : (2504688.542500, 2504688.542500)
10 : (1252344.271250, 1252344.271250)
12 : (626172.135625, 626172.135625)
14 : (313086.067812, 313086.067812)
16 : (156543.033906, 156543.033906)
18 : (78271.516953, 78271.516953)
20 : (39135.758477, 39135.758477)
22 : (19567.879238, 19567.879238)
24 : (9783.939619, 9783.939619)
26 : (4891.969810, 4891.969810)
28 : (2445.984905, 2445.984905)
30 : (1222.992452, 1222.992452)
32 : (611.496226, 611.496226)
34 : (305.748113, 305.748113)
36 : (152.874057, 152.874057)
38 : (76.437028, 76.437028)
40 : (38.218514, 38.218514)
42 : (19.109257, 19.109257)
44 : (9.554629, 9.554629)
46 : (4.777314, 4.777314)
48 : (2.388657, 2.388657)
50 : (1.194329, 1.194329)
52 : (0.597164, 0.597164)
54 : (0.298582, 0.298582)
56 : (0.149291, 0.149291)
58 : (0.074646, 0.074646)
60 : (0.037323, 0.037323)
62 : (0.018661, 0.018661)
64 : (0.009331, 0.009331)

Did I get something wrong here? Please advise...

**Comment by arjunmehta** [comment]
@hellocomrade hi!!

It's a good question. I can't seem to find that particular code in yinqiwen's repo. Can you point me to its context? (Ie line number and file)

I can explain how it works, and can explain why those numbers are the approximate matches to bit depths, but I'm curious where that for loop came from first :)

**Comment by hellocomrade** [comment]
@arjunmehta Thank you for the reply!

I came to your repos from a stackoverflow thread when you explained to someone how geohash works for bbox search on point dataset.

Here is the doc you referred to in your answer:
https://github.com/yinqiwen/ardb/blob/master/doc/spatial-index.md

It has a list of "radius" based upon bit depth.

However, it does look like the diameter to me in terms of the way they were calculated!

Could you please shed some light on this?

Thanks again!

**Comment by arjunmehta** [comment]
Ah sorry, I don't understand what is happening in your for loop to generate the values. What is `wmRange`? What is `naiveDecodeGeohash` and `naiveEncodeGeohash` doing and where did the values `4842397.8495074, -10601981.5353662` come from? That doesn't look like a geo-coordinate.

It looks like you're creating a bunch of scaled boxes based on the same proportion? All your numbers are just multiples of the same base size. Something to note, the box sizes will differ based on the latitude of the query.

You can see how the module/algorithm is working in this [article I wrote up and illustrated](http://23.239.12.206:8000/posts/2014-04-05-geohash-proximity-pt2.html). Hopefully it'll explain what is happening and possibly you can see the correlation with your results.

**Comment by hellocomrade** [comment]
Hi,

Thank you so much for sharing this great article. Truly great work! I just come over to let you know it may take some time for me to get back to you on this. I will need to read through it.

Best regards!

**Comment by hellocomrade** [comment]
@arjunmehta 
Hi,

After reading your article, I was able to put some source together for "educational" purpose.

https://github.com/hellocomrade/happygis/blob/master/morton.cpp

You can find the implementation of "naiveDecodeGeohash" and "naiveEncodeGeohash" in there.

[4842397.8495074, -10601981.5353662] are valid coordinates in Google Web Mercator, which has a bbox: (-20037508.34,-20037508.34,20037508.34,20037508.34). The reason I chose epsg:3857 instead of epsg: 4326 was to simplify the plane coordinate to facilitate the discussion. 

You mentioned "the box sizes will differ based on the latitude of the query.", is the box size considered as identical at the same bit-depth level? Correct me if I am wrong.

By reading your article, I kind of understand why this array is considered as the sequence of "radius": since we need to pick up 9 cells for the query, the radius is actually the length of the cell (well, if we simplify the case by using epsg:3857, all cells are square, correct me if I am wrong again) in the worst case. This will cover the edge case if the central lat/lon is located on the side of the central cell.

However, in your article, you mentioned: in order to conduct the range query, you will have to find the min/max for each cell in the 9 candidates and then you can apply ZRANGEBYSCORE against Redis. The way to find the max of a cell is by adding one onto the geohash value at the proper bit depth to cover the search radius and then left-shift the bits to meet the precision of the geohashed points.

Given geohash value 12, adding one to it will get 13, which is not in the 9 candidate cells at all. So, any point has hash value 13 should be excluded in the query. However, ZRANGEBYSCORE on min/max are inclusive on both min and max. Will this generate a false positive? (I do understand we will filter all candidates by actually calculating the distances)

I apologize if you already have had this part implemented in your code, I had a hard time to find the functions for neighbors. I can't find the answer from yinwiqen's latest code either:

https://github.com/yinqiwen/ardb/blob/da4742787867b89560b5e7743a698531bf82d359/src/common/geo/geohash.c

Could you please help me find the last missing piece of the puzzle?

Many thanks!

**Comment by hellocomrade** [comment]
I think I may answer myself here:

In Redis doc, it seems both max and min are inclusive:
http://redis.io/commands/ZRANGEBYSCORE

However, if you read the source:
https://github.com/antirez/redis/blob/unstable/src/geo.c#L281

"Compute the sorted set scores min (inclusive), max (exclusive)"

Allright, we can come back to my original question if you don't mind:

var rangeIndex = [
    0.6, //52
    1, //50
    2.19, //48
    4.57, //46
    9.34, //44
    14.4, //42
    33.18, //40
    62.1, //38
    128.55, //36
    252.9, //34
    510.02, //32
    1015.8, //30
    2236.5, //28
    3866.9, //26
    8749.7, //24
    15664, //22
    33163.5, //20
    72226.3, //18
    150350, //16
    306600, //14
    474640, //12
    1099600, //10
    2349600, //8
    4849600, //6
    10018863 //4
];

Could you please let me know how you came this numbers? And if my guess in the previous comment: "By reading your article, I kind of understand why this array is considered as the sequence of "radius": since we need to pick up 9 cells for the query, the radius is actually the length of the cell (well, if we simplify the case by using epsg:3857, all cells are square, correct me if I am wrong again) in the worst case. This will cover the edge case if the central lat/lon is located on the side of the central cell.", make any sense to you?

Many thanks!

**Comment by arjunmehta** [comment]
Hey there @hellocomrade ,
I am not sure about `epsg:3857` but it seems like it may be a great way to square up projections.

The thing about geohashes is that they refer to a box, WITHOUT any kind of projection system. So as you go further north (for example) the any box at a specific bit depth will get more and more narrow. To answer your question about whether box sizes == bitdepth, yes... kind of  :)

Honestly though the numbers in the array were pulled directly from yinqiwen's table. You should ask over in his repo. But I believe they account for this and maybe average out the sizing?

You can create a similar index by using something like my [geo-box](https://github.com/arjunmehta/node-geo-box) module to find average box sizes. Or even better, find an ideal size for a given radius at a specific latitude.

As you mentioned, you need to find box bit depths that when multiplied by 3, roughly equal a radius value. Another way of doing it is to find a box big enough that the circle fits into, and then filter by distance anything outside of the circle, but of course that has performance issues.

**Comment by hellocomrade** [comment]
Hi @arjunmehta ,

Again, I apologize for the late reply! Yes, epsg:3857 is the GIS world buzz word for reference to Google Mercator projection, it's used to be epsg:900913 and you can tell why it was coded that way:)

You mentioned that array I questioned is from yinqiwen's work. However, it seems that the numbers don't match anymore with his master branch.

Actually, you may want to consider changing the way for estimating the bit depth. See Redis Implementation: https://github.com/antirez/redis/blob/unstable/deps/geohash-int/geohash_helper.c#L59
which is more easy to understand and maintain, IMHO.

With all due respect, after exposing to this geohash-int for two weeks, I am still not very clear on why this is better than a traditional quadtree implementation. Quadtree is more intuitive to understand and implement. It also provides same time complexity as geohash for range search. I can understand that Redis may prefer geohash over Quadtree since geohash is able to downgrade 2D data to 1D and fits into Redis's Set data structure well so it doesn't need to implement a new structure specifically for spatial data. Other than this, I feel lost but I do know everything exists for a reason.

So, what's the main reason for applying geohash on spatial query, could you please enlighten me a bit?

BTW, what tool did you use for creating those svgs in your article, they look so cool!!! :)

**Comment by arjunmehta** [comment]
@hellocomrade Thanks for the questions and I appreciate the inquiry. I must say I don't quite have the bandwidth to answer all your questions, so I'll close this issue after this comment and leave the answers to all your questions for your own independent research to uncover.

This module was made as a port of Yinqiwen's work at the time. I was using his numbers as a base. Looks like he's made it more accurate now which is great.

Maybe you could ask antirez or yinqiwen why geohash is preferred over quadtree. Can't say I have an answer there. It's the same algorithm used with Redis, MongoDB, and ardb. So, other than the obvious (can be queried by score/ranking) and support for globe wrapping, I can't give more insight.

The SVGs were made using Adobe Illustrator and SMIL animation. Painstakingly! :)

Hope this helps. Will close this issue now, as it's not really an issue.

**Comment by hellocomrade** [comment]
@arjunmehta 

Thank you so much for all the advice and more importantly, timely responses!

You have been very patient and considerate to me! I really appreciate!

Wish the best to you! :)
