### ISSUE TITLE
Need performance test comparing node-geo-proximity to MongoDB spatial indexing

### ISSUE THREAD

**Issue by markusr** [arjunmehta/node-geo-proximity#3]
Hi,

really interesting project. Have you done any testing of the performance. Especially a compassion to mongodb's integrated  geospatial index?

See: http://docs.mongodb.org/manual/applications/geospatial-indexes/ 

Thanks 
 Markus

**Comment by arjunmehta** [comment]
Closing this. Won't be a priority. [Benchmarks comparing Native Redis Geo Commands](https://github.com/arjunmehta/node-geo-proximity/blob/3.0.0/test/benchmark.js) are included in v3.0.0 and more relevant
